name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read

    steps:
      - uses: actions/checkout@v3

      - name: Checkout testlib
        run: |
          git submodule update --init --recursive

      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build
        run: |
          cmake -DCMAKE_BUILD_TYPE:STRING=Debug -B ./build -G "Unix Makefiles"
          cmake --build ./build --config Debug --target all -j 18

      - name: Test
        run: |
          cd ./build
          sudo ctest --verbose

      - name: Print Log
        if: failure()
        run: |
          cat build/*.log
